### ISSUE TITLE
Clean and parse traffic count/turning movement count data

### ISSUE THREAD

**Issue by alchenist** [Data4Democracy/boston-crash-modeling#13]
Necessary for #9 -- traffic count data is currently holed away in individual .xls files. Includes both automated traffic recordings (ATRs) and turning movement counts (TMCs). Two major components:
-  [x] Clean the data and get it into a tidy format
-  [x] Make the data geospatial (i.e. geocode ATR locations)
-  [ ] Scrape data from TMCs and bind to segements

**Comment by keshavramaswamy** [comment]
Hi @alchenist - what type of format is preferred?
* Should the individual .xls files be cleaned and merged (on a suitable index) - then be uploaded as a single datasource to the data.world repo ? 
or  does cleaning the individual files  and uploading them separately like https://data.world/data4democracy/boston-crash-model/file/AUTOMATED%20TRAFFICE%20RECORDING%2F6795_NA_NA_59_BEAUMONT-ST_DORCHESTER_24-HOURS_CLASSIFICATION_09-11-2012.XLS alone suffice?

**Comment by alchenist** [comment]
@keshavramaswamy Individual clean files would be fine for our purposes if that's what you have, although Google Drive might be a better repository for individual files than data.world. Also, any Jupyter notebooks you used can be submitted in a PR to this repo!

**Comment by keshavramaswamy** [comment]
Awesome, thanks @alchenist - will use Drive then! Once I am done, i'll submit PRs too.

**Comment by anmolsjoshi** [comment]
Is this still an open issue? I can help contribute.

**Comment by andhint** [comment]
@anmolsjoshi I'm working on this currently. I'm almost done with the ATRs if you wanted to help with the TMC's let me know. (it should be a pretty similar process)

**Comment by anmolsjoshi** [comment]
Sounds good to me. How can I help?

**Comment by andhint** [comment]
@anmolsjoshi Are you in our slack channel? It'd probably be better to give you info there

**Comment by bpben** [comment]
@andhint do you think you could update this issue? Seems like you've done most of the work here, but a new issue needs to be filed with TMC, is that right?

**Comment by andhint** [comment]
@bpben Yeah I could do that, ATRs are done but we still need to discuss what needs to be done with the TMCs

**Comment by races1986** [comment]
picking up this for the hackathon....

**Comment by races1986** [comment]
submitted #29 which parses 144 of the 400 files in the directory

**Comment by bpben** [comment]
@j-t-t mind giving a quick update here on this? Maybe it makes sense to close this, open a new issue related to doing descriptives?

**Comment by j-t-t** [comment]
I need to do a little cleanup to get the output in a nice format.  Right now they're bound to segments (although I need to dig in a little to make sure these are accurate), and there's overall volume count.

But I think it will may be hard to use this in the predictive model since less than 5% of intersections have turning movement count data?

But things I'd still like to do on this:
-See if there's any correlation between the turning movement count volumes and crashes
-See if there's any correlation between 'conflicts' (as Amine suggested) and crashes
-I think it would be nice to combine volume counts between the ATRs and TMCs and put it somewhere.

Any other things I should be checking?  Maybe discuss this evening?

**Comment by bpben** [comment]
This seems done, at least the preliminary steps.  Also requires a lot of custom work.  Closing for now.
